services:
  university-db:
    image: postgres:17
    container_name: university-db
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: university
      POSTGRES_PASSWORD: university
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  university-redis:
    image: redis:8.2.1
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: